modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"

[[mods]] #mandatory

modId = "magicion"
version = "${file.jarVersion}"
displayName = "Magicion"
authors="Rue Development"
description = '''
Magicion is a tiny mod aiming to expend the magic in Minecraft.
This mod adds new magical content such as enchantments, illagers or potions, as well as introducing a whole new system with magic where the player can cast their own simple combinations of spells!
'''